### ISSUE TITLE
[BUG]t-pose error

### ISSUE THREAD

**Issue by RUFOS1** [Cruze03/FortniteEmotesNDances#5]
Even after doing the steps to solve the t-pose, it remains, I checked the folders, and they did not exist, then I ran the mm_download_addon command, and I also manually registered the workshop item, and the t-pose error.
Are there any other steps to take?

 - MetaMod version: 2.0 - build 1314
 - CounterStrikeSharp Version:  v286
 - OS:LINUX
 - Plugin Version: v1.0.5

**Comment by Cruze03** [comment]
Try manually placing vpk file in your server. Couple more people are facing this issue. Not really this plugin issue

**Comment by RUFOS1** [comment]
I did this and the error still persisted, removing the mod and cfg files from multiaddons, and deleting the folders, and I still continue with t-pose, even without the mod, would this perhaps indicate that the error is somewhere else?

**Comment by Cruze03** [comment]
Tagged you in discord to discuss this further
